import { describe, expect, test, beforeAll, afterAll } from "bun:test";
import { initContext, runWithDirectory } from "../src/ctx";
import { researchInit } from "../src/tools/init";
import { ResearchTimeline } from "../src/timeline";
import { stubAccessor, stubAuth, stubCache, stubCtx } from "./helpers";
import type { ToolResult } from "@ericsanchezok/synergy-plugin";
import path from "path";
import fs from "fs/promises";
import YAML from "yaml";

// ── Setup ────────────────────────────────────────────────────────────────────

const TMP = path.join(process.env.TMPDIR || "/tmp", `holos-scholens-layout-${Date.now()}`);

function fullState(project: string) {
  return {
    project,
    anchor: "Scholens-backed research",
    schema_version: 2,
    created: "2026-01-01T00:00:00Z",
    updated: "2026-01-01T00:00:00Z",
    config: {
      participation_mode: "collaborative",
      venue: "ICML 2027",
      stalled_days: 7,
      exploration: {
        depth: "standard",
        pilot: "enabled",
        max_refine_rounds: 3,
        idea_select_score: 8,
        idea_generators: 3,
      },
      ground: { max_review_rounds: 2, max_closest_works: 3 },
      design: { max_review_rounds: 5, score_threshold: 7, max_primary_claims: 2, max_new_components: 2 },
      experiment: {
        max_optimize_rounds: 3,
        monitor_interval: "30m",
        significance_level: 0.05,
        min_seeds: 3,
        regression_tolerance: 0.05,
      },
      realize: {
        max_review_rounds: 3,
        code_review_threshold: 7,
        require_sanity_contract: true,
        require_quality_contract: true,
      },
      compose: { max_revise_rounds: 3 },
    },
    counters: { idea: 0, plan: 0, exp: 0, claim: 0, exh: 0, paper: 0, sub: 0 },
    focus: {
      since: "2026-01-01T00:00:00Z",
      phase: "explore",
      reason: "Project initialized — starting with exploration",
      blocked_on: null,
    },
  };
}

async function initCtx() {
  initContext({ directory: TMP, config: stubAccessor() as any, auth: stubAuth() as any, cache: stubCache() as any });
}

async function callInit(params: Record<string, unknown>) {
  return researchInit.execute(params as any, stubCtx) as Promise<ToolResult>;
}

// Prevent research_init's auto `git init`+commit from running during fresh-init
// tests: a pre-existing .git dir makes init treat the scope as already git'd.
async function precreateGitDir(base: string) {
  await fs.mkdir(path.join(base, ".git"), { recursive: true });
}

/** Seed a legacy (upstream-generated) project under `base`: .research skeleton + old AGENTS.md. */
async function seedLegacyProject(base: string, project: string) {
  const rd = path.join(base, ".research");
  await fs.mkdir(rd, { recursive: true });
  await fs.mkdir(path.join(rd, "ideas"), { recursive: true });
  await fs.mkdir(path.join(rd, "literature", "papers"), { recursive: true });
  await Bun.write(path.join(rd, "state.yaml"), YAML.stringify(fullState(project)));
  await Bun.write(path.join(rd, "timeline.jsonl"), "");
  // Legacy AGENTS.md generated by the upstream holos-research plugin.
  const legacyAgentsMd = `# ${project}

<!-- DYNAMIC_STATE_START -->
## Current Research State
(placeholder)
<!-- DYNAMIC_STATE_END -->

## Critical Operating Rules

- \`research_wiki\` — ingest papers, register gaps, link relationships whenever you discover relevant work
- \`research_state\` — read/update project state
`;
  await Bun.write(path.join(base, "AGENTS.md"), legacyAgentsMd);
}

// ── Test 1: fresh init creates docs/surveys, never .research/literature ─────

describe("research_init Scholens layout", () => {
  const dir = path.join(TMP, "fresh");
  let firstInitOutput = "";

  beforeAll(async () => {
    await initCtx();
    await runWithDirectory(dir, async () => {
      await precreateGitDir(dir);
      const result = await callInit({ project: "Fresh Scholens Project", anchor: "test anchor" });
      firstInitOutput = result.output;
      expect(result.title).toBe("Fresh Scholens Project");
    });
  });

  afterAll(async () => {
    await fs.rm(TMP, { recursive: true, force: true });
  });

  test("creates docs/surveys at scope root", async () => {
    await runWithDirectory(dir, async () => {
      const surveys = await fs
        .stat(path.join(dir, "docs", "surveys"))
        .then(() => true)
        .catch(() => false);
      expect(surveys).toBe(true);
    });
  });

  test("does NOT create .research/literature", async () => {
    await runWithDirectory(dir, async () => {
      const lit = await fs
        .stat(path.join(dir, ".research", "literature"))
        .then(() => true)
        .catch(() => false);
      expect(lit).toBe(false);
    });
  });

  test("does NOT write literature stubs (no gap_map/edges/bib)", async () => {
    await runWithDirectory(dir, async () => {
      const rd = path.join(dir, ".research");
      for (const f of ["literature/gap_map.yaml", "literature/edges.jsonl", "literature/references.bib"]) {
        const exists = await fs
          .stat(path.join(rd, f))
          .then(() => true)
          .catch(() => false);
        expect(exists).toBe(false);
      }
    });
  });

  test("init output advertises docs/surveys and not literature", () => {
    expect(firstInitOutput).toContain("docs/surveys/");
    expect(firstInitOutput).not.toContain(".research/literature/");
  });
});

// ── Test 2: legacy AGENTS.md referencing research_wiki is regenerated ───────

describe("research_init legacy AGENTS.md migration (K8)", () => {
  const dir = path.join(TMP, "legacy");

  beforeAll(async () => {
    await initCtx();
    await runWithDirectory(dir, async () => {
      await seedLegacyProject(dir, "Legacy Project");
    });
  });

  afterAll(async () => {
    await fs.rm(TMP, { recursive: true, force: true });
  });

  test("reload regenerates AGENTS.md once when it references research_wiki", async () => {
    await runWithDirectory(dir, async () => {
      await callInit({ project: "Legacy Project", anchor: "x" });
      const agentsMd = await Bun.file(path.join(dir, "AGENTS.md")).text();
      expect(agentsMd).not.toContain("research_wiki");
      // New template's Scholens literature convention is present.
      expect(agentsMd).toContain("Scholens");
    });
  });

  test("legacy .research/literature directory is left untouched (K7)", async () => {
    await runWithDirectory(dir, async () => {
      const rd = path.join(dir, ".research");
      const papersDir = await fs
        .stat(path.join(rd, "literature", "papers"))
        .then(() => true)
        .catch(() => false);
      expect(papersDir).toBe(true); // not deleted
      const stateYaml = await Bun.file(path.join(rd, "state.yaml")).text();
      expect(stateYaml).toContain("Legacy Project"); // not rewritten/reset
    });
  });
});

// ── Test 3: legacy timeline with wiki.* event types still parses ────────────

describe("legacy timeline wiki.* event compatibility (K9)", () => {
  const dir = path.join(TMP, "timeline");

  beforeAll(async () => {
    await initCtx();
    await runWithDirectory(dir, async () => {
      const rd = path.join(dir, ".research");
      await fs.mkdir(rd, { recursive: true });
      await Bun.write(path.join(rd, "state.yaml"), YAML.stringify(fullState("Timeline Project")));
      await Bun.write(
        path.join(rd, "timeline.jsonl"),
        [
          JSON.stringify({
            ts: "2026-01-02T00:00:00Z",
            type: "wiki.paper_ingested",
            id: "chen2025_gap",
            summary: "ingested paper",
          }),
          JSON.stringify({
            ts: "2026-01-03T00:00:00Z",
            type: "wiki.gap_registered",
            id: "G01",
            summary: "registered gap",
          }),
          JSON.stringify({ ts: "2026-01-04T00:00:00Z", type: "idea.created", id: "idea_001", summary: "created idea" }),
        ].join("\n") + "\n",
      );
    });
  });

  afterAll(async () => {
    await fs.rm(TMP, { recursive: true, force: true });
  });

  test("wiki.* events parse and are returned by timeline query", async () => {
    await runWithDirectory(dir, async () => {
      const events = await ResearchTimeline.query();
      expect(events).toHaveLength(3);
      const types = events.map((e) => e.type);
      expect(types).toContain("wiki.paper_ingested");
      expect(types).toContain("wiki.gap_registered");
      expect(types).toContain("idea.created");
    });
  });

  test("TimelineEventType still accepts wiki.* values", async () => {
    await runWithDirectory(dir, async () => {
      const events = await ResearchTimeline.query();
      for (const e of events) {
        expect(e.type).toBeTruthy();
      }
    });
  });
});
